### ISSUE TITLE
Contract page token holdings

### ISSUE THREAD

**Issue by saimeunt** [walnuthq/op-scan#42] opened 2024-07-29 01:16 UTC
# Contract page holdings

## ⚠️ Reading contributors guidelines to get assigned is MANDATORY!

[Read contributors guidelines](https://github.com/walnuthq/op-scan/issues/1)

## User stories

As a user, when I access a contract page, I want to see all the contract token holdings both in token quantity and dollar value, I want to see every ERC20 as well as ERC721/1155 for NFTs.
When I click on the token holdings combobox, I can search for a particular token by name, and it should display some details about the selected token holding, such as quantity, dollar value and the spot price taken to compute the current dollar value.

## Validation

It should look like the Etherscan contract page token holdings, eg. https://optimistic.etherscan.io/address/0x5ae97e4770b7034c7ca99ab7edc26a18a23cb412

![Image](https://github.com/user-attachments/assets/4540e1f5-fd66-4d95-922f-65a52a694f28)

Do NOT implement a dedicated token holdings page, it will be done in a separate issue.
Stick to the minimum viable feature, do NOT implement token holdings sorting.

## Implementation

Use the combobox component from shadcn/ui.
For token prices, you can use the [Coinbase spot price API](https://api.coinbase.com/v2/prices/USD/spot), feel free to use something else if you find a better alternative.
This feature will highly benefit from using an indexer to keep track of the contract token holdings, for the time being it's okay to build an MVP of the feature by tracking token transfers from the most recent blocks and using these logs to fetch the contract balance of the specific tokens found in the latest logs.

## Resources

- shadcn/ui combobox: https://ui.shadcn.com/docs/components/combobox
- Coinbase spot price API: https://docs.cdp.coinbase.com/sign-in-with-coinbase/docs/api-prices/#get-spot-price
- ERC20 token transfers in transaction details page: https://github.com/walnuthq/op-scan/blob/main/src/lib/utils.ts#L77

**Comment by ShantelPeters** [comment] 2024-07-29 01:23
Please can I be assigned to work on this issue,this is my first time applying for an issue

**Comment by coxmars** [comment] 2024-07-29 01:29
Hi @saimeunt I hope you're well. I'd like to apply for the issue involving the combobox component from shadcn/ui. Here's my plan:

Token Prices: Use the Coinbase spot price API (open to alternatives).
Indexer: Benefit from an indexer to track contract token holdings.
MVP: Track token transfers from recent blocks and fetch contract balances from these logs.
Could you assign this issue to me? I have worked on this project before so I know the structure 🚀🫡

**Comment by danielcdz** [comment] 2024-07-29 01:38
Hello @saimeunt I already contributed to this project in the last ODHack, I want to help with this issue if possible, I will do the following:

- I will use a library like viem, combined with a smart-contract ABI to interact with it, retrieve the latest blocks, and search for the token balance in the last logs.
- Having this information I will use the CoinBase Spot API to calculate the prices(I will check for other APIs, or options).
-  I will use the `shadcn/ui combobox` to show the results in the ERC20 token transfers in transaction details page.

**Comment by melnikga** [comment] 2024-07-29 04:22
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/opscan).

### My background and how it can be leveraged
I can take this

I've worked with a lot of Walnut projects and I'm ready to tackle this issue.
In the OP scan project, I was developing token transfers in tx details page (#13 )

### How I plan on tackling this issue
The file https://github.com/walnuthq/op-scan/blob/main/src/lib/contracts/erc-20/contract.ts it was developed by me at the previous hackathon, therefore it will not be difficult for me to make a similar component using the Table from shadcn again.
My profile on OnlyDust: https://app.onlydust.com/u/melnikga

**Comment by josephchimebuka** [comment] 2024-07-29 04:37
Hello @saimeunt  I am a software developer and I am proficient in Reactjs, typescript, nextjs, solidity I am contributed to some projects on Odhack here is my profile https://app.onlydust.com/u/josephchimebuka and here are couple of projects I have worked on https://bethelapp.com/ metacrypt.vercel.app 

Here's how I plan to handle the issue

1. Fetch Token Data
   Integrate APIs to fetch token holdings and prices for ERC20 and ERC721/1155 tokens.

2. Design UI Components
   Create a layout with sections for token holdings and a searchable combobox.
    Ensure the design resembles Etherscan's token holdings page.

3. Add Search Functionality:
    Implement a combobox to search for tokens by name.
   -Display details (quantity, dollar value, spot price) for the selected token.

5. Validate Against Etherscan:
   Ensure the UI and data match the format and accuracy of Etherscan's contract page token holdings.

6. Testing and Deployment:
   Test to ensure compatibility.

**Comment by jaipaljadeja** [comment] 2024-07-29 07:40
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/opscan).

### My background and how it can be leveraged
i can take this : )

**Comment by Benjtalkshow** [comment] 2024-07-29 10:18
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/opscan).

### My background and how it can be leveraged
@saimeunt
I'm excited about the opportunity to contribute to the Op Scan Project again. Having successfully implemented the block details page during the last ODHack, I'm keen to bring the same level of quality and dedication to this new task. With my background in Next.js, TypeScript, Shadcn, and React, I'm confident I can deliver an efficient and user-friendly Contract Token Holdings feature.

### How I plan on tackling this issue
### Proposed Solution for Contract Page Token Holdings
## Component Creation:

- I will create a new component for displaying token holdings on the contract page.
- The component will show both `ERC20 and ERC721/1155 (NFT)` holdings.

## Data Fetching and Processing:

- I will implement a system to track token transfers from recent blocks.
- Using these logs, I'll fetch the contract balance for specific tokens found in the latest logs.
I'll integrate the `Coinbase spot price API` (or a suitable alternative) to fetch token prices for dollar value calculations.

## Advanced and Fast Fetching Techniques:

- I will implement server-side rendering (SSR) with `getServerSideProps` for initial data loading.

## UI Components:

- I will implement a `combobox` using the `shadcn/ui` component for token selection and search.
- The design will closely resemble the Etherscan contract page token holdings.
- The combobox will allow users to search for tokens by name.
- When a token is selected, I'll display details including quantity, dollar value, and the spot price used for calculations.

## Token Holdings Display:

- I will show token holdings in both token quantity and dollar value.
- The display will include all ERC20 tokens and ERC721/1155 for NFTs.

I hope to get this issue assigned to me. i will deliver an excellent work. Thanks

**Comment by Blumebee** [comment] 2024-07-29 12:02
@coxmars @jaipaljadeja @danielcdz @josephchimebuka @melnikga @ShantelPeters Hi all! If you haven't yet done so, please apply to the issue via OnlyDust! It will make it much easier to assign. Maintainers will be assigning through the platform.

https://app.onlydust.com/hackathons/odhack-60

**Comment by danielcdz** [comment] 2024-07-29 13:48
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/opscan).

### My background and how it can be leveraged
Hello, my name is Daniel Calderon I already contributed to this project in the last ODHack! I'm from Costa Rica and I have about 3 years of experience as a backend engineer, and also I'm an active OSS contributor in OnlyDust

### How I plan on tackling this issue

- I will use a library like viem and a smart-contract ABI to interact with it, retrieve the latest blocks, and search for the token balance in the last logs.
- Having this information I will use the CoinBase Spot API to calculate the prices(I will check for other APIs, or options).
-  I will use the `shadcn/ui combobox` to show the results in the ERC20 token transfers in transaction details page.
 - I will check the results and confirm that the user stories are done.

**Comment by jrmncos** [comment] 2024-07-30 04:38
I am applying to this issue via [OnlyDust platform](https://app.onlydust.com/p/opscan).

### My background and how it can be leveraged
hey team! I'm a backend software engineer with more than 5 years of experience (but web2, I will not lie) I'm migrating to web3, so I would like to work on this one

### How I plan on tackling this issue
the issue is very self explanatory (better than my job) I'll do it

**Closed as completed** 2024-08-09 14:21 UTC
Labels: OD Hack
